version: "3.8"

services:
  backend:
    build:
      context: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"      # Map host 8000 to container 8000

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  
    volumes:
      - ./nginx-temp.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/ai.smartprojects.dev/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ai.smartprojects.dev/privkey.pem:/etc/ssl/certs/privkey.pem:ro